// <auto-generated />
using System;
using AutoDexApi.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoDexApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519222452_FixInitial")]
    partial class FixInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoDexApi.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MotorcycleId");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Mark")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<int>("YearManufacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AutoDexApi.Models.VehicleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Acceleration")
                        .HasColumnType("double");

                    b.Property<string>("Engine")
                        .HasColumnType("longtext");

                    b.Property<string>("FuelType")
                        .HasColumnType("longtext");

                    b.Property<int>("MaximumSpeed")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasColumnType("longtext");

                    b.Property<int?>("VehicleId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleInfos");
                });

            modelBuilder.Entity("AutoDexApi.Models.Car", b =>
                {
                    b.HasBaseType("AutoDexApi.Models.Vehicle");

                    b.Property<string>("Doors")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Traction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeSteering")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("AutoDexApi.Models.Motorcycle", b =>
                {
                    b.HasBaseType("AutoDexApi.Models.Vehicle");

                    b.Property<string>("BrakeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EngineDisplacement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeHandlebar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Motorcycles", (string)null);
                });

            modelBuilder.Entity("AutoDexApi.Models.VehicleInfo", b =>
                {
                    b.HasOne("AutoDexApi.Models.Vehicle", "Vehicle")
                        .WithOne("Info")
                        .HasForeignKey("AutoDexApi.Models.VehicleInfo", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoDexApi.Models.Car", b =>
                {
                    b.HasOne("AutoDexApi.Models.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("AutoDexApi.Models.Car", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoDexApi.Models.Motorcycle", b =>
                {
                    b.HasOne("AutoDexApi.Models.Vehicle", null)
                        .WithOne()
                        .HasForeignKey("AutoDexApi.Models.Motorcycle", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoDexApi.Models.Vehicle", b =>
                {
                    b.Navigation("Info");
                });
#pragma warning restore 612, 618
        }
    }
}
