// <auto-generated />
using System;
using AutoDexApi.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoDexApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519030512_AddTPCWithFK")]
    partial class AddTPCWithFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoDexApi.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Mark")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<int>("YearManufacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("AutoDexApi.Models.VehicleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Acceleration")
                        .HasColumnType("double");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Engine")
                        .HasColumnType("longtext");

                    b.Property<string>("FuelType")
                        .HasColumnType("longtext");

                    b.Property<int>("MaximumSpeed")
                        .HasColumnType("int");

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("MotorcycleId")
                        .IsUnique();

                    b.ToTable("VehicleInfos");
                });

            modelBuilder.Entity("AutoDexApi.Models.Car", b =>
                {
                    b.HasBaseType("AutoDexApi.Models.Vehicle");

                    b.Property<string>("Doors")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Traction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeSteering")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("AutoDexApi.Models.Motorcycle", b =>
                {
                    b.HasBaseType("AutoDexApi.Models.Vehicle");

                    b.Property<string>("BrakeType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EngineDisplacement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeHandlebar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Motorcycles", (string)null);
                });

            modelBuilder.Entity("AutoDexApi.Models.VehicleInfo", b =>
                {
                    b.HasOne("AutoDexApi.Models.Car", "Car")
                        .WithOne("Info")
                        .HasForeignKey("AutoDexApi.Models.VehicleInfo", "CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoDexApi.Models.Motorcycle", "Motorcycle")
                        .WithOne("Info")
                        .HasForeignKey("AutoDexApi.Models.VehicleInfo", "MotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Car");

                    b.Navigation("Motorcycle");
                });

            modelBuilder.Entity("AutoDexApi.Models.Car", b =>
                {
                    b.Navigation("Info");
                });

            modelBuilder.Entity("AutoDexApi.Models.Motorcycle", b =>
                {
                    b.Navigation("Info");
                });
#pragma warning restore 612, 618
        }
    }
}
