// <auto-generated />
using AutoDexApi.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoDexApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250516220709_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoDexApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Doors")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("Infosid")
                        .HasColumnType("int");

                    b.Property<string>("Mark")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Traction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeSteering")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("YearManufacture")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Infosid");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("AutoDexApi.Models.VehicleInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Acceleration")
                        .HasColumnType("double");

                    b.Property<string>("Engine")
                        .HasColumnType("longtext");

                    b.Property<string>("FuelType")
                        .HasColumnType("longtext");

                    b.Property<int>("MaximumSpeed")
                        .HasColumnType("int");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("VehicleInfo");
                });

            modelBuilder.Entity("AutoDexApi.Models.Car", b =>
                {
                    b.HasOne("AutoDexApi.Models.VehicleInfo", "Infos")
                        .WithMany()
                        .HasForeignKey("Infosid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Infos");
                });
#pragma warning restore 612, 618
        }
    }
}
